
name: remote ssh command
on: [workflow_dispatch]
jobs:
  install-build-deploy:
    runs-on: ubuntu-latest
    env:
#      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
#     ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_USER_ID: ${{ secrets.AZURE_USER_ID }}
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      AZURE_TENANT: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 23.97.167.204
        username: "ofer"
        password: "QWEasd112233"
        port: 22
        script:
          whoami ;
          pwd;
          az login --service-principal --username ${{ secrets.AZURE_USER_ID }} --password ${{ secrets.AZURE_PASSWORD }} --tenant ${{ secrets.AZURE_AD_TENANT_ID }} --subscription 3acbc334-72a0-4b2d-b3bb-8498810f4955;
          az aks get-credentials --resource-group itg-cellcom-prod-rg --name itg-cellcom-prod-1-aks  --admin;
          `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`;
          sudo apt-get update;
          sudo apt-get install -y apt-transport-https ca-certificates curl;
          `curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"`;
          sudo snap install helm --classic;
          `helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo`;
          `helm install mongodb-release azure-marketplace/mongodb`;
          helm install redis-release azure-marketplace/redis
           
           
        
          
  

 

