name: Terraform new-apply

on: [workflow_dispatch]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: login to azure
        run: | 
          az login --service-principal --username $oferm@cloudvalley.io --password "QWErty90()" --tenant "edb35e24-c305-4216-8a2e-3bc074765d16"


    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: "52.149.230.147"
        username: "ofer"
        password: "QWEasd112233"
        port: 22
        script: 
          whoami
          ls -l 
          pwd
