name: Terraform new-apply

on: [workflow_dispatch]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false


    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan

      # On push to master, build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
#      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
    
    
    - name: Call terraform output
      id: terraform-output
      run: |
        echo ::set-output name=admin_password::$(terraform output admin_pswd)
        echo ::set-output name=admin_user::$(terraform output admin_username)
        echo ::set-output name=ip_address::$(terraform output vm_public_ip_address)

    
    - name: disply terraform output
      run: | 
        echo ${{steps.terraform-output.outputs.ip_address}}
        echo ${{steps.terraform-output.outputs.admin_user}}
        echo ${{steps.terraform-output.outputs.admin_password}}
        


 #       echo "$(terraform output admin_pswd)"
        
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host:     ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port:      22
        script: 
          az aks get-credentials --resource-group itg-cellcom-prod-rg --name itg-cellcom-prod-4-aks  --admin; 
          `curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash`;
          sudo apt-get update;
          sudo apt-get install -y apt-transport-https ca-certificates curl;
          `curl -LO https://dl.k8s.io/${curl -L -s https://dl.k8s.io/release/stable.txt}/bin/linux/amd64/kubectl.sha256`;
          sudo snap install helm --classic;
          `helm repo add azure-marketplace https://marketplace.azurecr.io/helm/v1/repo`;
          `helm install mongodb-release azure-marketplace/mongodb`;
          helm install redis-release azure-marketplace/redis;
